### ISSUE TITLE
Remove any Pro assets from this repository

### ISSUE THREAD

**Issue by robmadole** [quintronsystems/font-awesome-java#1]
Ref:

https://github.com/FortAwesome/Font-Awesome-Pro/issues/948#issuecomment-403140505

Hey there @quintronsystems. I'm a developer on the Font Awesome project and I noticed that you have an asset that is part of our paid commercial product, Font Awesome Pro.

Can you remove this? Specifically a Pro file in the `src/com/quintron/FontAwesome/Fonts` directory called `fa-light-300.ttf`.

**Comment by quintronsystems** [comment]
Thanks for noticing that.  We use this project internally using pro, so I guess my import script fails to clean up a file. 

I've isolated my build enviornment for our local build and this repo so that our pro version doesn't touch this project anymore. 

Thanks.
